Exception: Resource 'xxx' does not exist [ID-NN7GD] (bug 494976) https://bugs.eclipse.org/bugs/show_bug.cgi?id=494976
git-svn-id: https://dev.eclipse.org/svnroot/technology/org.eclipse.subversive/trunk@21580 ee007c2a-0a25-0410-9ab9-bf268980928c